openapi: 3.0.3
info:
  title: Books API
  description: A simple RESTful API for managing books using Gin and GORM
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Development server

paths:
  /api/books:
    get:
      summary: List all books
      description: Returns a list of all books in the database
      operationId: getBooks
      responses:
        '200':
          description: A list of books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
        '500':
          description: Internal server error
    post:
      summary: Create a new book
      description: Creates a new book in the database
      operationId: createBook
      requestBody:
        required: true
        content:
          application/json:
            schema:
   ...  Hide contents