name: dagger

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  issue_comment:
    types: [created]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run tests
        id: test
        uses: dagger/dagger-for-github@8.0.0
        with:
          version: "0.18.8"
          verb: call
          args: test
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}

  update-changelog:
    name: update-changelog
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'issue_comment' &&
      github.event.issue.pull_request &&
      contains(github.event.comment.body, '/update-changelog')
    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: refs/pull/${{ github.event.issue.number }}/merge
      - name: Update changelog
        uses: dagger/dagger-for-github@8.0.0
        with:
          version: "0.18.8"
          verb: call
          args: update-changelog --repository=${{ github.repository }} --ref=${{ github.ref_name }} --token=env://GITHUB_API_TOKEN
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL: "gpt-4o"
          GITHUB_API_TOKEN: ${{ secrets.GH_API_TOKEN }}
