name: dagger

on:
  #push:
  #  branches:
  #    - main
  #pull_request:
  #  branches:
  #    - main
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run tests
        id: test
        uses: dagger/dagger-for-github@8.0.0
        with:
          version: "0.18.8"
          verb: call
          args: test
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}

  update-changelog:
    name: update-changelog
    if: >
      github.event_name == 'issue_comment' &&
      contains(github.event.comment.body, 'update-changelog') &&
      github.event.issue.pull_request
    runs-on: ubuntu-latest
    steps:
      - name: Get PR details
        id: pr
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/${{ github.repository }}/pulls/${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Comment on PR
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: "Updating changelog..."
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ fromJson(steps.pr.outputs.data).head.ref }}
          repository: ${{ fromJson(steps.pr.outputs.data).head.repo.full_name }}
      - name: Update changelog
        uses: dagger/dagger-for-github@8.0.0
        with:
          version: "0.18.8"
          verb: call
          args: update-changelog --repository=${{ github.repository }} --ref=${{ fromJson(steps.pr.outputs.data).head.ref }} --token=env://GITHUB_API_TOKEN
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL: "gpt-4o"
          GITHUB_API_TOKEN: ${{ secrets.GH_API_TOKEN }}
